const quotes = [
	"What we cannot speak about we must pass over in silence.",
	"There are no questions left and this itself is the answer.",
	"Strange mixtures of ideas.",
	"Reality is distributed.",
	"The metapicture is the place where pictures reveal and ‘know’ themselves, where they reflect on the intersections of visuality, language, and similitude, where they engage in speculation and theorizing on their own nature and history.",
	"All that is solid melts into air, all that is sacred is profaned.",
	"Industry occurs in a rather more abstract topographic space, needing only to be at the crux of flows of energy, labor, and raw materials.",
	"Universalism, Communism, Disinterestedness, Organized Skepticism.",
	"It’s even been said that if people could see in high dimensions machine learning would not be necessary.",
	"Why would you want to picture it?",
	"Developing successful machine learning applications requires a substantial amount of “black art” and folk knowledge that is difficult to find in textbooks.",
	"Let’s use all of our knowledge to construct a computer program that knows.",
	"Designing such a program requires commitments about what knowledge is and how it is obtained. Thus, some of the major traditional problems of philosophy arise in artificial intelligence.",
	"Our intuitions, which come from a three-dimensional world, often do not apply in high-dimensional ones. In high dimensions, most of the volume of a high-dimensional orange is in the skin, not the pulp.",
	"He who would conceive a fourth dimension must be able to imagine a fourth axis perpendicular to all three of the others. ",
	"This clearly transcends all possibility even of imagination.",
	"Odd questions make sense here. What is the opposite of Canada?",
	"Intuitive concepts are rational concepts, i.e. intuition is Cartesian intuition.",
	"A high-dimensional orange has most of its volume in the pulp, not in the flesh.",
	"In high dimensions you can have donuts with many holes.",
	"I am an eye. A mechanical eye. I am the machine that reveals the world to you as only the machine can see it. I am now free of human immobility.",
	"Freed from the constraints of time and space, I organize each point of the universe as I wish. My route is that of a new conception of the world. I can make you discover the world you did not know existed.",
	"All things are vectors.",
	"Every diagram is intersocial and constantly evolving. It never functions in order to represent a persistent world but produces a new kind of reality, a new model of truth.",
	"Ways of Knowing.",
	"Inseparable differences start to disentangle themselves.",
	"I do not generally like trying to visualize thousand-dimensional vectors in three-dimensional space.",
	"Beyond that which we are incapable of visualizing is that which we are incapable of even understanding.",
	"I am the earth in the palm of your hand."
];